services:
  - type: web
    name: careerbot-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn careerbot:app --host 0.0.0.0 --port 10000"
    autoDeploy: true